import Head from "next/head";
import { Inter } from "next/font/google";
import { useContext, useEffect, useState } from "react";
import { AuthContext } from "@/store/AuthContext";
import axios from "axios";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const auth = useContext(AuthContext);
  const username = auth.username;
  const [problems, setProblems] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [showPopup, setShowPopup] = useState(false);
  const [inputValue, setInputValue] = useState("");

  const getProblems = async () => {
    setIsLoading(true);
    try {
      const res = await axios.get("https://abhayasha.onrender.com/getProblems");
      console.log(res.data);
      setProblems(res.data);
      setIsLoading(false);
    } catch (error) {
      console.error(error);
      setIsLoading(false);
    }
  };

  useEffect(() => {
    getProblems();
  }, []);

  const handleSubmit = (e) => {
    e.preventDefault();
    localStorage.setItem("visited", "true");
    setShowPopup(false);
  };

  const handleClose = () => {
    localStorage.setItem("visited", "true");
    setShowPopup(false);
  };

  useEffect(() => {
    const visited = localStorage.getItem("visited");
    if (!visited) {
      setShowPopup(true);
    }
  }, []);

  const Popup = ({ className }) => {
    return (
      <>
        <div className={className}>
          <div className="bg-white rounded-lg p-8">
            <h2 className="text-lg font-bold mb-4">
              Why are you visiting this page?
            </h2>
            <form onSubmit={handleSubmit}>
              <label className="block mb-4">
                <span className="text-gray-700">Reason:</span>
                <textarea
                  className="form-textarea mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                  rows="3"
                  placeholder="Enter your reason here"
                  value={inputValue}
                  onChange={(e) => setInputValue(e.target.value)}
                ></textarea>
              </label>
              <div className="flex justify-end">
                <button
                  className="mr-4 text-gray-600 hover:text-gray-800 font-medium"
                  type="button"
                  onClick={handleClose}
                >
                  Close
                </button>
                <button
                  className="bg-blue-500 text-white rounded-lg px-4 py-2"
                  type="submit"
                >
                  Submit
                </button>
              </div>
            </form>
          </div>
        </div>
      </>
    );
  };

  return (
    <>
      <Head>
        <title>Abhay Shah | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="h-[100vh] flex gap-5 justify-center items-center relative">
          {showPopup && (
            <Popup
              className={
                "fixed inset-0 bg-gray-500 bg-opacity-75 flex items-center justify-center"
              }
            />
          )}
          <div className="w-[23%] h-[90%] flex flex-col gap-10 overflow-y-auto">
            <div className="w-[95%] mx-auto">
              <span>NEWS ARCHIVE</span>
              <div className="w-full block h-[50vh] bg-gray-200"></div>
            </div>
            <div className="w-[95%] mx-auto">
              <span>EVENTS ARCHIVE</span>
              <div className="w-full block h-[50vh] bg-gray-200"></div>
            </div>
          </div>
          <div className="w-[65%] h-[90%] flex flex-col overflow-y-auto">
            <div className="w-[95%] mx-auto mt-5 flex flex-col gap-10">
              <span className="text-6xl text-gray-800">WELCOME</span>
              <div className="flex flex-col gap-5">
                <span className="border-2 bg-[#3b83f638] text-[#3B82F6] border-[#3B82F6] flex justify-center items-center py-3 text-xl">
                  Problems of the Day
                </span>
                {isLoading && (
                  <div className="flex justify-center item-center">
                    Loading...
                  </div>
                )}
                {problems.map((data, i) => {
                  return (
                    <div key={i} className="flex flex-col">
                      <span>
                        Q{i + 1}. {data?.question}
                      </span>
                      <textarea
                        className="border-2 outline-none px-3 py-2"
                        name="answerone"
                        placeholder="Type your answer here"
                        id="answerone"
                        cols="122"
                        rows="10"
                      ></textarea>
                      <button className="bg-[#3B82F6] px-2 py-1 text-white w-20">
                        Submit
                      </button>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
