import Head from "next/head";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Abhay Shah | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="h-[100vh] flex gap-5 justify-center items-center">
          <div className="w-[23%] h-[90%] flex flex-col gap-10 overflow-y-auto">
            <div className="w-[95%] mx-auto">
              <span>NEWS ARCHIVE</span>
              <div className="w-full block h-[50vh] bg-gray-200"></div>
            </div>
            <div className="w-[95%] mx-auto">
              <span>EVENTS ARCHIVE</span>
              <div className="w-full block h-[50vh] bg-gray-200"></div>
            </div>
          </div>
          <div className="w-[65%] h-[90%] flex flex-col overflow-y-auto">
            <div className="w-[95%] mx-auto mt-5 flex flex-col gap-10">
              <span className="text-6xl">WELCOME</span>
              <div className="flex flex-col gap-5">
                <span className="border-2 bg-[#3b83f638] text-[#3B82F6] border-[#3B82F6] flex justify-center items-center py-3 text-xl">
                  Problems of the Day
                </span>
                <div>
                  <span>
                    Q1. Lorem ipsum dolor sit amet consectetur adipisicing elit
                    ipsum debitis ex saepe nulla libero, temporibus unde
                    ratione?
                  </span>
                  <textarea
                    className="border-2 outline-none px-3 py-2"
                    name="answerone"
                    placeholder="Type your answer here"
                    id="answerone"
                    cols="122"
                    rows="10"
                  ></textarea>
                  <button className="bg-[#3B82F6] px-2 py-1 text-white w-20">
                    Submit
                  </button>
                </div>
                <div>
                  <span>
                    Q2. Lorem ipsum dolor sit amet consectetur adipisicing elit
                    ipsum debitis ex saepe nulla libero, temporibus unde
                    ratione?
                  </span>
                  <textarea
                    className="border-2 outline-none px-3 py-2"
                    name="answertwo"
                    placeholder="Type your answer here"
                    id="answertwo"
                    cols="122"
                    rows="10"
                  ></textarea>
                  <button className="bg-[#3B82F6] px-2 py-1 text-white w-20">
                    Submit
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
